config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tasks
  root 'top#index'
  resource :login, only: %i[ new create ]
  resource :logout, only: %i[show]
  
  resources :welcomes, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :name , presence: true 
    validates :age, numericality: { only_integer: true}, presence: true
    def self.hello_world
        'Hello, World!!'
    end

    def say_hello
        'Hello!!'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    helper_method :current_user
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
def new
end

def create
    user = User.where(name: params[:name], age: params[:age]).first

    if user.present?
        session[:user_id] = user.id
        redirect_to users_path, notice: 'ログインしました'
    else
        flash.now[:warning] = 'ログインできませんでした'
        render :new
    end
end
end

app/controllers/logouts_controller.rb
class LogoutsController < ApplicationController
def show
    session.delete(:user_id)
    redirect_to root_path, notice: 'ログアウトしました'

end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]

    def index
        @tasks = Task.all
        @index_title = 'タスク一覧'
    end

    def show
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            redirect_to @task, notice: 'タスクの新規登録に成功しました'
        else
            render :new
        end
    end

    def edit
    end

    def update
        respond_to do |format|
            if @task.update(task_params)
                format.html { redirect_to task_url(@task), notice: "タスクの更新に成功しました"}
                format.json { render :show, status: :ok, location: @task}
            end
        end
    end

    def destroy
        @task.destroy

        respond_to do |format|
            format.html { redirect_to tasks_url}
            format.json { head :no_content}
        end
    end

    private

    def set_task
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:title, :description, :due_date)
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :set_index_title, only: :index
  before_action :set_show_title, only: :show
  

  # GET /users or /users.json
  def index
   
    @users = User.where(age: 20..50).order(age: :desc)
    @index_title = 'ユーザー一覧'
   
    
  end

  # GET /users/1 or /users/1.json
  def show
   @show_title = 'ユーザー詳細'
  end

  # GET /users/new
  def new
    @user = User.new
    @user.name = 'らんてくん'
    @user.age = 20
    

  end

  # GET /users/1/edit
  def edit
  end

def user_params
  params.require(:user).permit(:name, :age, :address, :tel)
end 

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "ユーザーの新規登録に成功しました" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "ユーザーの更新に成功しました" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :address, :tel)
    end

    def set_index_title
      @index_title = 'ユーザー一覧'
    end

    def set_show_title
      @show_title = 'ユーザー詳細'
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  layout false

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RUNTEQ Rails入門STEPアプリ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">RUNTEQ Rails入門STEPアプリ</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="col-md-3 text-end">
        <% if current_user.present? %>
          <span class="btn btn-primary"><%= current_user.name %></span>
          <%= link_to 'ログアウト', root_path, class: 'btn btn-outline-primary me-2' %>
      <% else %>
        <%= link_to 'ログイン', new_login_path, class: 'btn btn-outline-primary me-2' %>
      <% end %>
        </div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'トップ', root_path, class: 'nav-link active', 'aria-current': 'page' %>
                <%= link_to 'ユーザー', users_path, class: 'nav-link active', 'aria-current': 'page' %>
                <%= link_to 'タスク', tasks_path, class: 'nav-link active', 'aria-current': 'page' %>
                </li>
            </ul>
          </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/logins/new.html.erb
<h1>ログイン</h1>

<%= form_with(url: login_path) do |form| %>
  <div>
    <%= form.label :name, '名前', style: "display: block" %>
    <%= form.text_field :name, value: params[:name] %>
  </div>

  <div>
    <%= form.label :age, '年齢', style: "display: block" %>
    <%= form.text_field :age, value: params[:age] %>
  </div>
  
  <div>
   <%= form.submit 'ログイン' %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
    <% if task.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div>
        <%= form.label :title, 'タイトル', style: "display: block" %>
        <%= form.text_field :title %>
      </div>

      <div>
        <%= form.label :description, '内容', style: "display: block" %>
        <%= form.text_area :description %>
      </div>

      <div>
        <%= form.submit '登録' %>
      </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
   <p>
    <strong>タイトル:</strong>
    <%= task.title %>
   </p>

   <p>
     <strong>内容:</strong>
     <%= task.description %>
    </p>
</div>

app/views/tasks/edit.html.erb
<h1>編集</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "詳細", @task %>
  <%= link_to "一覧", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @index_title %></h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "詳細", task %>
    </p>
    <% end %>
</div>

    <%= link_to "新規作成", new_task_path %>

app/views/tasks/new.html.erb
<h1>新規作成</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "一覧", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>
<h1><%= @show_title %></h1>

<%= render @task %>

<div>
  <%= link_to "編集", edit_task_path(@task) %>
  <%= link_to "一覧", tasks_path %>

  <%= button_to "削除", @task, method: :delete %>
</div> 

app/views/top/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">トップ</h1>
</div>
<h2>このページは例です</h2>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>random</td>
        <td>data</td>
        <td>placeholder</td>
        <td>text</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>placeholder</td>
        <td>irrelevant</td>
        <td>visual</td>
        <td>layout</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>data</td>
        <td>rich</td>
        <td>dashboard</td>
        <td>tabular</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>information</td>
        <td>placeholder</td>
        <td>illustrative</td>
        <td>data</td>
      </tr>
      <tr>
        <td>1,004</td>
        <td>text</td>
        <td>random</td>
        <td>layout</td>
        <td>dashboard</td>
      </tr>
      <tr>
        <td>1,005</td>
        <td>dashboard</td>
        <td>irrelevant</td>
        <td>text</td>
        <td>placeholder</td>
      </tr>
      <tr>
        <td>1,006</td>
        <td>dashboard</td>
        <td>illustrative</td>
        <td>rich</td>
        <td>data</td>
      </tr>
      <tr>
        <td>1,007</td>
        <td>placeholder</td>
        <td>tabular</td>
        <td>information</td>
        <td>irrelevant</td>
      </tr>
      <tr>
        <td>1,008</td>
        <td>random</td>
        <td>data</td>
        <td>placeholder</td>
        <td>text</td>
      </tr>
      <tr>
        <td>1,009</td>
        <td>placeholder</td>
        <td>irrelevant</td>
        <td>visual</td>
        <td>layout</td>
      </tr>
      <tr>
        <td>1,010</td>
        <td>data</td>
        <td>rich</td>
        <td>dashboard</td>
        <td>tabular</td>
      </tr>
      <tr>
        <td>1,011</td>
        <td>information</td>
        <td>placeholder</td>
        <td>illustrative</td>
        <td>data</td>
      </tr>
      <tr>
        <td>1,012</td>
        <td>text</td>
        <td>placeholder</td>
        <td>layout</td>
        <td>dashboard</td>
      </tr>
      <tr>
        <td>1,013</td>
        <td>dashboard</td>
        <td>irrelevant</td>
        <td>text</td>
        <td>visual</td>
      </tr>
      <tr>
        <td>1,014</td>
        <td>dashboard</td>
        <td>illustrative</td>
        <td>rich</td>
        <td>data</td>
      </tr>
      <tr>
        <td>1,015</td>
        <td>random</td>
        <td>tabular</td>
        <td>information</td>
        <td>text</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, '名前', style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, '年齢', style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
   <%= form.label :tel , '電話番号', style: "display: block" %>
   <%= form.telephone_field :tel %>
   </div>

   <div>
   <%= form.label :address , '住所', style:  "display: block" %>
   <%= form.text_field :address %>
   </div>

  <div>
    <%= form.submit '登録' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>名前:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>年齢:</strong>
    <%= user.age %>
  </p>

  <p>
  <strong>電話番号:</strong>
  <%= user.tel %>
  </p>

  <p>
  <strong>住所:</strong>
  <%= user.address %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>編集</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "詳細", @user %> |
  <%= link_to "一覧", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @index_title %></h1>

<div id="users">
  <% @users.each do |user| %>
<%= render user %>

    <p>
      <%= link_to "詳細", user %>
    </p>
  <% end %>

</div>

<%= link_to "新規作成", new_user_path %>

app/views/users/new.html.erb
<h1>新規作成</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "一覧", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<h1><%= @show_title %></h1>
<%= render @user %>

<div>
  <%= link_to "編集", edit_user_path(@user) %> |
  <%= link_to "一覧", users_path %>

  <%= button_to "削除", @user, method: :delete %>
</div>